export const FIJAR_SECCION = 'FIJAR_SECCION'
export const FIJAR_SUBSECCION = 'FIJAR_SUBSECCION'
export const FIJAR_CONTENIDO = 'FIJAR_CONTENIDO'
export const DESTACAR_MARCADOR = 'DESTACAR_MARCADOR'
export const MOSTRAR_POPUP = 'MOSTRAR_POPUP'

export const AGREGAR_MARCADOR = 'AGREGAR_MARCADOR'
export const ELIMINAR_MARCADOR = 'ELIMINAR_MARCADOR'

export const FIJAR_DESTINO = 'FIJAR_DESTINO'

export const MOSTRAR_LOGIN = 'MOSTRAR_LOGIN'
export const FIJAR_USUARIO = 'FIJAR_USUARIO'