export const FIJAR_SECCION = 'FIJAR_SECCION'
export const FIJAR_SUBSECCION = 'FIJAR_SUBSECCION'

export const FIJAR_CONTENIDO = 'FIJAR_CONTENIDO'

export const AGREGAR_MARCADOR = 'AGREGAR_MARCADOR'
export const ELIMINAR_MARCADOR = 'ELIMINAR_MARCADOR'